Repository ros2/rclcpp, pull requests merged in 2018-09, with the labels that each got.

#546 Doc fixups
  rclcpp/include/rclcpp/executors/multi_threaded_executor.hpp
  rclcpp/include/rclcpp/node.hpp
  rclcpp/include/rclcpp/subscription.hpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
Labels: in review

#545 Get node names and namespaces
  rclcpp/include/rclcpp/node_interfaces/node_graph.hpp
  rclcpp/include/rclcpp/node_interfaces/node_graph_interface.hpp
  rclcpp/src/rclcpp/node_interfaces/node_graph.cpp
Labels: in progress

#553 Make sure timer is fini'd before clock
  rclcpp/src/rclcpp/timer.cpp
Labels: in review

#557 Output rcl error message when yaml parsing fails
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
Labels: in review

#558 Add max_duration to spin_some()
  rclcpp/include/rclcpp/executor.hpp
  rclcpp/src/rclcpp/executor.cpp
Labels: enhancement, in review

#556 Fix cpplint on xenial
  rclcpp/src/rclcpp/clock.cpp
Labels: in review

#559 Don't auto-activate ROS time if clock topic is being published
  rclcpp/include/rclcpp/time_source.hpp
  rclcpp/src/rclcpp/time_source.cpp
  rclcpp/test/test_time_source.cpp
Labels: in review
