Repository ros2/rclcpp, pull requests merged in 2018-06, with the labels that each got.

#481 Split ParameterVariant into Parameter and ParameterValue
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/node.hpp
  rclcpp/include/rclcpp/node_impl.hpp
  rclcpp/include/rclcpp/node_interfaces/node_parameters.hpp
  rclcpp/include/rclcpp/node_interfaces/node_parameters_interface.hpp
  rclcpp/include/rclcpp/parameter.hpp
  rclcpp/include/rclcpp/parameter_client.hpp
  rclcpp/include/rclcpp/parameter_value.hpp
  rclcpp/include/rclcpp/rclcpp.hpp
  rclcpp/src/rclcpp/node.cpp
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
  rclcpp/src/rclcpp/parameter.cpp
  rclcpp/src/rclcpp/parameter_client.cpp
  rclcpp/src/rclcpp/parameter_service.cpp
  rclcpp/src/rclcpp/parameter_value.cpp
  rclcpp/src/rclcpp/time_source.cpp
  rclcpp/test/test_parameter.cpp
  rclcpp/test/test_time_source.cpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node_impl.hpp
  rclcpp_lifecycle/src/lifecycle_node.cpp
Labels: in review

#480 Subscription tests using bind in member callback
  rclcpp/test/test_subscription.cpp
Labels: in review

#489 fully delete parameters
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
  rclcpp/src/rclcpp/parameter_value.cpp
  rclcpp/test/test_parameter.cpp
Labels: bug, in review

#485 Convert rcl_params_t to ParameterMap
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/exceptions.hpp
  rclcpp/include/rclcpp/parameter_map.hpp
  rclcpp/package.xml
  rclcpp/src/rclcpp/parameter_map.cpp
  rclcpp/test/test_parameter_map.cpp
Labels: in review

#486 Pass initial parameter values to node constructor
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/node.hpp
  rclcpp/include/rclcpp/node_interfaces/node_parameters.hpp
  rclcpp/src/rclcpp/node.cpp
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
  rclcpp/test/test_node_global_args.cpp
  rclcpp/test/test_node_initial_parameters.cpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
  rclcpp_lifecycle/src/lifecycle_node.cpp
Labels: in review

#493 Get parameters that aren't set
  rclcpp/include/rclcpp/node_interfaces/node_parameters_interface.hpp
  rclcpp/src/rclcpp/parameter_service.cpp
Labels: bug, in review

#494 add missing set_parameters_atomically client
  rclcpp/src/rclcpp/parameter_client.cpp
Labels: in review

#497 use size_t
  rclcpp/include/rclcpp/message_memory_strategy.hpp
Labels: in progress

#498 always get service name from rcl to account for remapping
  rclcpp/include/rclcpp/client.hpp
  rclcpp/include/rclcpp/service.hpp
  rclcpp/src/rclcpp/client.cpp
  rclcpp/src/rclcpp/executor.cpp
  rclcpp/src/rclcpp/service.cpp
Labels: enhancement, in review

#388 *_raw function
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/create_subscription.hpp
  rclcpp/include/rclcpp/message_memory_strategy.hpp
  rclcpp/include/rclcpp/node.hpp
  rclcpp/include/rclcpp/node_impl.hpp
  rclcpp/include/rclcpp/parameter_client.hpp
  rclcpp/include/rclcpp/publisher.hpp
  rclcpp/include/rclcpp/subscription.hpp
  rclcpp/include/rclcpp/subscription_factory.hpp
  rclcpp/include/rclcpp/subscription_traits.hpp
  rclcpp/package.xml
  rclcpp/src/rclcpp/executor.cpp
  rclcpp/src/rclcpp/parameter_client.cpp
  rclcpp/src/rclcpp/subscription.cpp
  rclcpp/src/rclcpp/time_source.cpp
  rclcpp/test/test_serialized_message_allocator.cpp
  rclcpp/test/test_subscription_traits.cpp
  rclcpp_lifecycle/src/lifecycle_node_interface_impl.hpp
Labels: in review

#452 fix tests due to changes in rcutils
  rclcpp/test/test_logging.cpp
Labels: enhancement, in review

#500 comply to new subscription template
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node_impl.hpp
  rclcpp_lifecycle/test/test_lifecycle_node.cpp
Labels: in review

#383 executor could take more than once incorrectly
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/executors/multi_threaded_executor.hpp
  rclcpp/src/rclcpp/executors/multi_threaded_executor.cpp
  rclcpp/test/executors/test_multi_threaded_executor.cpp
Labels: bug, in review

#501 Further expand test tolerance to address flakiness.
  rclcpp/test/executors/test_multi_threaded_executor.cpp
Labels: in review

#502 typo
  rclcpp/include/rclcpp/node.hpp
Labels: in review

#505 keep shared pointer reference to rcl_node handle for subscription fini
  rclcpp/src/rclcpp/subscription.cpp
Labels: bug, in review
