Repository ros2/rclcpp, pull requests merged in 2018-12, with the labels that each got.

#597 Allow removing a waitable
  rclcpp/include/rclcpp/callback_group.hpp
  rclcpp/include/rclcpp/node_interfaces/node_waitables.hpp
  rclcpp/include/rclcpp/node_interfaces/node_waitables_interface.hpp
  rclcpp/src/rclcpp/callback_group.cpp
  rclcpp/src/rclcpp/node_interfaces/node_waitables.cpp
Labels: enhancement, in review

#594 [rclcpp_action] Action client implementation
  rclcpp_action/include/rclcpp_action/client.hpp
  rclcpp_action/include/rclcpp_action/client_goal_handle.hpp
  rclcpp_action/include/rclcpp_action/client_goal_handle_impl.hpp
  rclcpp_action/include/rclcpp_action/create_client.hpp
  rclcpp_action/include/rclcpp_action/exceptions.hpp
  rclcpp_action/include/rclcpp_action/types.hpp
  rclcpp_action/src/client.cpp
  rclcpp_action/test/test_client.cpp
Labels: in progress

#593 rclcpp_action Server implementation
  rclcpp_action/CMakeLists.txt
  rclcpp_action/include/rclcpp_action/create_server.hpp
  rclcpp_action/include/rclcpp_action/server.hpp
  rclcpp_action/include/rclcpp_action/server_goal_handle.hpp
  rclcpp_action/include/rclcpp_action/server_goal_handle_impl.hpp
  rclcpp_action/include/rclcpp_action/types.hpp
  rclcpp_action/src/server.cpp
  rclcpp_action/src/server_goal_handle.cpp
  rclcpp_action/src/types.cpp
  rclcpp_action/test/test_server.cpp
Labels: in progress

#602 Adapt to action implicit field changes
  rclcpp_action/include/rclcpp_action/client.hpp
  rclcpp_action/include/rclcpp_action/server.hpp
  rclcpp_action/include/rclcpp_action/server_goal_handle.hpp
  rclcpp_action/test/test_client.cpp
  rclcpp_action/test/test_server.cpp
Labels: in review

#598 add wait_for_action_server() for action clients
  .gitignore
  rclcpp/src/rclcpp/client.cpp
  rclcpp_action/include/rclcpp_action/client.hpp
  rclcpp_action/include/rclcpp_action/client_goal_handle_impl.hpp
  rclcpp_action/include/rclcpp_action/create_client.hpp
  rclcpp_action/src/client.cpp
  rclcpp_action/src/server.cpp
Labels: enhancement, in review

#605 defer signal handling to a singleton thread
  rclcpp/include/rclcpp/context.hpp
  rclcpp/include/rclcpp/graph_listener.hpp
  rclcpp/include/rclcpp/utilities.hpp
  rclcpp/src/rclcpp/context.cpp
  rclcpp/src/rclcpp/executor.cpp
  rclcpp/src/rclcpp/graph_listener.cpp
  rclcpp/src/rclcpp/utilities.cpp
Labels: bug, in review

#611 move destructors to top of class
  rclcpp/include/rclcpp/node_interfaces/node_base_interface.hpp
  rclcpp/include/rclcpp/node_interfaces/node_clock_interface.hpp
  rclcpp/include/rclcpp/node_interfaces/node_graph_interface.hpp
  rclcpp/include/rclcpp/node_interfaces/node_logging_interface.hpp
  rclcpp/include/rclcpp/node_interfaces/node_parameters_interface.hpp
  rclcpp/include/rclcpp/node_interfaces/node_services_interface.hpp
  rclcpp/include/rclcpp/node_interfaces/node_timers_interface.hpp
  rclcpp/include/rclcpp/node_interfaces/node_topics_interface.hpp
  rclcpp/include/rclcpp/node_interfaces/node_waitables_interface.hpp
Labels: in review

#607 use signal safe synchronization with platform specific semaphores
  rclcpp/CMakeLists.txt
  rclcpp/src/rclcpp/signal_handler.cpp
  rclcpp/src/rclcpp/signal_handler.hpp
  rclcpp/src/rclcpp/utilities.cpp
Labels: enhancement, in review

#612 Added new constructors for SyncParameterClient
  rclcpp/include/rclcpp/parameter_client.hpp
  rclcpp/src/rclcpp/parameter_client.cpp
Labels: in review

#613 Fix errors from uncrustify v0.68
  rclcpp/include/rclcpp/function_traits.hpp
Labels: in review
