Repository ros2/rclcpp, pull requests merged in 2018-05, with the labels that each got.

#468 Fini arguments passed to rcl_node_init()
  rclcpp/src/rclcpp/node_interfaces/node_base.cpp
Labels: in progress

#470 Fix bug when mixing shared_ptr and bind.
  rclcpp_lifecycle/test/test_register_custom_callbacks.cpp
Labels: bug, in review

#443 Adding parameter array support
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/parameter.hpp
  rclcpp/src/rclcpp/parameter.cpp
  rclcpp/test/test_parameter.cpp
Labels: in review

#476 Workaround for wait_for_service lasting the full timeout with connext
  rclcpp/src/rclcpp/client.cpp
Labels: in review

#478 Autostart parameter services
  rclcpp/include/rclcpp/create_service.hpp
  rclcpp/include/rclcpp/node.hpp
  rclcpp/include/rclcpp/node_impl.hpp
  rclcpp/include/rclcpp/node_interfaces/node_parameters.hpp
  rclcpp/include/rclcpp/parameter_service.hpp
  rclcpp/src/rclcpp/node.cpp
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
  rclcpp/src/rclcpp/parameter_service.cpp
  rclcpp/test/test_time_source.cpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node_impl.hpp
  rclcpp_lifecycle/src/lifecycle_node.cpp
Labels: in review

#483 Spin before checking if ros time is active
  rclcpp/test/test_time_source.cpp
Labels: in review

#474 Use rosgraph_msgs/Clock for /clock topic.
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/time_source.hpp
  rclcpp/package.xml
  rclcpp/src/rclcpp/time_source.cpp
  rclcpp/test/test_time_source.cpp
Labels: in review
