Repository ros2/rclcpp, pull requests merged in 2018-03, with the labels that each got.

#445 update style
  rclcpp/include/rclcpp/allocator/allocator_deleter.hpp
  rclcpp/include/rclcpp/any_service_callback.hpp
  rclcpp/include/rclcpp/any_subscription_callback.hpp
  rclcpp/include/rclcpp/function_traits.hpp
  rclcpp/include/rclcpp/intra_process_manager_impl.hpp
  rclcpp/include/rclcpp/node_interfaces/node_parameters_interface.hpp
  rclcpp/include/rclcpp/publisher_factory.hpp
  rclcpp/include/rclcpp/service.hpp
  rclcpp/include/rclcpp/strategies/allocator_memory_strategy.hpp
  rclcpp/include/rclcpp/subscription.hpp
  rclcpp/include/rclcpp/subscription_factory.hpp
  rclcpp/src/rclcpp/executor.cpp
  rclcpp/src/rclcpp/parameter.cpp
  rclcpp_lifecycle/src/lifecycle_node_interface_impl.hpp
Labels: in review

#431 Store the subscriber, client, service and timer
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/client.hpp
  rclcpp/include/rclcpp/memory_strategy.hpp
  rclcpp/include/rclcpp/service.hpp
  rclcpp/include/rclcpp/strategies/allocator_memory_strategy.hpp
  rclcpp/include/rclcpp/subscription.hpp
  rclcpp/include/rclcpp/timer.hpp
  rclcpp/src/rclcpp/client.cpp
  rclcpp/src/rclcpp/executor.cpp
  rclcpp/src/rclcpp/memory_strategy.cpp
  rclcpp/src/rclcpp/service.cpp
  rclcpp/src/rclcpp/subscription.cpp
  rclcpp/src/rclcpp/timer.cpp
Labels: enhancement, in review

#448 Revert "Store the subscriber, client, service and timer"
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/client.hpp
  rclcpp/include/rclcpp/memory_strategy.hpp
  rclcpp/include/rclcpp/service.hpp
  rclcpp/include/rclcpp/strategies/allocator_memory_strategy.hpp
  rclcpp/include/rclcpp/subscription.hpp
  rclcpp/include/rclcpp/timer.hpp
  rclcpp/src/rclcpp/client.cpp
  rclcpp/src/rclcpp/executor.cpp
  rclcpp/src/rclcpp/memory_strategy.cpp
  rclcpp/src/rclcpp/service.cpp
  rclcpp/src/rclcpp/subscription.cpp
  rclcpp/src/rclcpp/timer.cpp
Labels: in progress

#451 make log location parameter const
  rclcpp/test/test_logging.cpp
Labels: enhancement, in review

#449 Revert "Revert "Store the subscriber, client, service and timer""
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/client.hpp
  rclcpp/include/rclcpp/memory_strategy.hpp
  rclcpp/include/rclcpp/service.hpp
  rclcpp/include/rclcpp/strategies/allocator_memory_strategy.hpp
  rclcpp/include/rclcpp/subscription.hpp
  rclcpp/include/rclcpp/timer.hpp
  rclcpp/src/rclcpp/client.cpp
  rclcpp/src/rclcpp/executor.cpp
  rclcpp/src/rclcpp/memory_strategy.cpp
  rclcpp/src/rclcpp/service.cpp
  rclcpp/src/rclcpp/subscription.cpp
  rclcpp/src/rclcpp/timer.cpp
  rclcpp/test/test_externally_defined_services.cpp
  rclcpp/test/test_find_weak_nodes.cpp
  rclcpp/test/test_logging.cpp
Labels: in review

#453 Fix time type issue in time unittest
  rclcpp/test/test_time.cpp
Labels: bug, in review

#446 change export order for static linking
  rclcpp/CMakeLists.txt
  rclcpp_lifecycle/CMakeLists.txt
Labels: in progress

#454 Remove ros arguments
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/utilities.hpp
  rclcpp/src/rclcpp/utilities.cpp
  rclcpp/test/test_utilities.cpp
Labels: in progress

#442 Add argument for thread count to multithreaded executor
  rclcpp/include/rclcpp/executors/multi_threaded_executor.hpp
  rclcpp/src/rclcpp/executors/multi_threaded_executor.cpp
Labels: in review

#435 handle node names which are null
  rclcpp/src/rclcpp/node_interfaces/node_graph.cpp
Labels: in review
