Repository ros2/rclcpp, pull requests merged in 2018-11, with the labels that each got.

#576 delete TRANSITION_SHUTDOWN
  rclcpp_lifecycle/src/lifecycle_node_interface_impl.hpp
Labels: in review

#577 use new error handling API from rcutils
  rclcpp/include/rclcpp/message_memory_strategy.hpp
  rclcpp/include/rclcpp/service.hpp
  rclcpp/include/rclcpp/strategies/allocator_memory_strategy.hpp
  rclcpp/src/rclcpp/client.cpp
  rclcpp/src/rclcpp/exceptions.cpp
  rclcpp/src/rclcpp/executor.cpp
  rclcpp/src/rclcpp/expand_topic_or_service_name.cpp
  rclcpp/src/rclcpp/node_interfaces/node_base.cpp
  rclcpp/src/rclcpp/node_interfaces/node_graph.cpp
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
  rclcpp/src/rclcpp/node_interfaces/node_services.cpp
  rclcpp/src/rclcpp/node_interfaces/node_timers.cpp
  rclcpp/src/rclcpp/node_interfaces/node_topics.cpp
  rclcpp/src/rclcpp/publisher.cpp
  rclcpp/src/rclcpp/subscription.cpp
  rclcpp/src/rclcpp/timer.cpp
  rclcpp/src/rclcpp/utilities.cpp
  rclcpp_lifecycle/src/lifecycle_node_interface_impl.hpp
Labels: enhancement, in review

#586 Update rcl_wait_set_add_* calls
  rclcpp/include/rclcpp/strategies/allocator_memory_strategy.hpp
  rclcpp/src/rclcpp/graph_listener.cpp
Labels: in review

#579 Skeleton for Action Server and Client
  rclcpp_action/CMakeLists.txt
  rclcpp_action/include/rclcpp_action/client.hpp
  rclcpp_action/include/rclcpp_action/client_goal_handle.hpp
  rclcpp_action/include/rclcpp_action/client_goal_handle_impl.hpp
  rclcpp_action/include/rclcpp_action/create_client.hpp
  rclcpp_action/include/rclcpp_action/create_server.hpp
  rclcpp_action/include/rclcpp_action/rclcpp_action.hpp
  rclcpp_action/include/rclcpp_action/server.hpp
  rclcpp_action/include/rclcpp_action/server_goal_handle.hpp
  rclcpp_action/include/rclcpp_action/server_goal_handle_impl.hpp
  rclcpp_action/include/rclcpp_action/visibility_control.hpp
  rclcpp_action/package.xml
  rclcpp_action/src/client.cpp
  rclcpp_action/src/server.cpp
  rclcpp_action/src/server_goal_handle.cpp
  rclcpp_action/test/test_client.cpp
  rclcpp_action/test/test_server.cpp
Labels: in progress

#589 [rclcpp] Add class Waitable
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/any_executable.hpp
  rclcpp/include/rclcpp/callback_group.hpp
  rclcpp/include/rclcpp/memory_strategy.hpp
  rclcpp/include/rclcpp/node.hpp
  rclcpp/include/rclcpp/node_interfaces/node_waitables.hpp
  rclcpp/include/rclcpp/node_interfaces/node_waitables_interface.hpp
  rclcpp/include/rclcpp/rclcpp.hpp
  rclcpp/include/rclcpp/strategies/allocator_memory_strategy.hpp
  rclcpp/include/rclcpp/waitable.hpp
  rclcpp/src/rclcpp/callback_group.cpp
  rclcpp/src/rclcpp/executor.cpp
  rclcpp/src/rclcpp/memory_strategy.cpp
  rclcpp/src/rclcpp/node.cpp
  rclcpp/src/rclcpp/node_interfaces/node_waitables.cpp
  rclcpp/src/rclcpp/waitable.cpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
  rclcpp_lifecycle/src/lifecycle_node.cpp
Labels: in review

#596 fix wrong use of constructor and hanging test
  rclcpp/test/test_time_source.cpp
Labels: bug, in review

#587 refactor init to allow for non-global init
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/client.hpp
  rclcpp/include/rclcpp/context.hpp
  rclcpp/include/rclcpp/executor.hpp
  rclcpp/include/rclcpp/executors/multi_threaded_executor.hpp
  rclcpp/include/rclcpp/executors/single_threaded_executor.hpp
  rclcpp/include/rclcpp/graph_listener.hpp
  rclcpp/include/rclcpp/init_options.hpp
  rclcpp/include/rclcpp/logger.hpp
  rclcpp/include/rclcpp/node.hpp
  rclcpp/include/rclcpp/node_impl.hpp
  rclcpp/include/rclcpp/node_interfaces/node_clock.hpp
  rclcpp/include/rclcpp/publisher.hpp
  rclcpp/include/rclcpp/service.hpp
  rclcpp/include/rclcpp/time_source.hpp
  rclcpp/include/rclcpp/timer.hpp
  rclcpp/include/rclcpp/utilities.hpp
  rclcpp/src/rclcpp/client.cpp
  rclcpp/src/rclcpp/context.cpp
  rclcpp/src/rclcpp/executor.cpp
  rclcpp/src/rclcpp/executors/multi_threaded_executor.cpp
  rclcpp/src/rclcpp/executors/single_threaded_executor.cpp
  rclcpp/src/rclcpp/graph_listener.cpp
  rclcpp/src/rclcpp/init_options.cpp
  rclcpp/src/rclcpp/logger.cpp
  rclcpp/src/rclcpp/node.cpp
  rclcpp/src/rclcpp/node_interfaces/node_base.cpp
  rclcpp/src/rclcpp/node_interfaces/node_clock.cpp
  rclcpp/src/rclcpp/node_interfaces/node_graph.cpp
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
  rclcpp/src/rclcpp/subscription.cpp
  rclcpp/src/rclcpp/time_source.cpp
  rclcpp/src/rclcpp/timer.cpp
  rclcpp/src/rclcpp/utilities.cpp
  rclcpp/test/test_init.cpp
  rclcpp/test/test_utilities.cpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node_impl.hpp
  rclcpp_lifecycle/src/lifecycle_node.cpp
Labels: enhancement, in review
