Repository ros2/rclcpp, pull requests merged in 2019-06, with the labels that each got.

#753 checking origin of intra-process msg before taking them
  rclcpp/include/rclcpp/subscription.hpp
Labels: in review

#757 Add rclcpp::create_timer()
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/create_timer.hpp
  rclcpp/include/rclcpp/node_interfaces/get_node_base_interface.hpp
  rclcpp/include/rclcpp/node_interfaces/get_node_timers_interface.hpp
  rclcpp/test/test_create_timer.cpp
Labels: enhancement

#756 Ignore parameters overrides in set parameter methods when allowing undeclared parameters
  rclcpp/include/rclcpp/node.hpp
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
  rclcpp/test/test_node.cpp
Labels: in review

#765 use default parameter descriptor in parameters interface
  rclcpp/include/rclcpp/node_interfaces/node_parameters_interface.hpp
Labels: enhancement

#767 Add ignore override argument to declare parameter
  rclcpp/include/rclcpp/node.hpp
  rclcpp/include/rclcpp/node_impl.hpp
  rclcpp/include/rclcpp/node_interfaces/node_parameters.hpp
  rclcpp/include/rclcpp/node_interfaces/node_parameters_interface.hpp
  rclcpp/src/rclcpp/node.cpp
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
  rclcpp/test/test_node.cpp
Labels: in review

#762 Use params from node '/**' from parameter YAML file
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
Labels: enhancement, in review

#771 Fix a comparison with a sign mismatch
  rclcpp/src/rclcpp/node_options.cpp
Labels: in review

#567 Adding a factory method to create a Duration from seconds
  rclcpp/include/rclcpp/duration.hpp
  rclcpp/src/rclcpp/duration.cpp
  rclcpp/test/test_duration.cpp
Labels: in review
