Repository ros2/rclcpp, pull requests merged in 2019-03, with the labels that each got.

#646 Attempt to fix cppcheck warning
  rclcpp/src/rclcpp/clock.cpp
Labels: bug, in review

#652 Add a method to the LifecycleNode class to get the logging interface
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
  rclcpp_lifecycle/src/lifecycle_node.cpp
Labels: in review

#601 update to use separated action types
  rclcpp_action/include/rclcpp_action/client.hpp
  rclcpp_action/include/rclcpp_action/client_goal_handle.hpp
  rclcpp_action/include/rclcpp_action/client_goal_handle_impl.hpp
  rclcpp_action/include/rclcpp_action/server.hpp
  rclcpp_action/include/rclcpp_action/server_goal_handle.hpp
  rclcpp_action/include/rclcpp_action/types.hpp
  rclcpp_action/src/client.cpp
  rclcpp_action/src/server.cpp
  rclcpp_action/src/types.cpp
  rclcpp_action/test/test_client.cpp
  rclcpp_action/test/test_server.cpp
Labels: in review

#648 Don't hardcode int64_t for duration type representations
  rclcpp/include/rclcpp/client.hpp
  rclcpp/include/rclcpp/executor.hpp
  rclcpp/include/rclcpp/executors.hpp
  rclcpp/include/rclcpp/node.hpp
  rclcpp/include/rclcpp/node_impl.hpp
  rclcpp/include/rclcpp/parameter_client.hpp
  rclcpp_action/include/rclcpp_action/client.hpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node_impl.hpp
Labels: in review

#639 Fix test_time_source test
  rclcpp/test/test_time_source.cpp
Labels: in review

#656 fix wait for service memory leak bug
  rclcpp/src/rclcpp/client.cpp
Labels: in review

#659 Using ament_target_dependencies where possible
  rclcpp/CMakeLists.txt
  rclcpp_lifecycle/CMakeLists.txt
Labels: in review

#662 Expose get_fully_qualified_name in Node API
  rclcpp/include/rclcpp/node.hpp
  rclcpp/include/rclcpp/node_interfaces/node_base.hpp
  rclcpp/include/rclcpp/node_interfaces/node_base_interface.hpp
  rclcpp/src/rclcpp/node.cpp
  rclcpp/src/rclcpp/node_interfaces/node_base.cpp
  rclcpp/test/test_node.cpp
Labels: in progress

#621 Avoid race that triggers timer too often
  rclcpp/include/rclcpp/executors/multi_threaded_executor.hpp
  rclcpp/src/rclcpp/executors/multi_threaded_executor.cpp
Labels: in review

#651 Fix use_sim_time issue on LifeCycleNode
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
  rclcpp_lifecycle/src/lifecycle_node.cpp
Labels: in review

#645 Add parameter-related templates to LifecycleNode
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node_impl.hpp
Labels: in review

#672 fix linter errors in rclcpp_lifecycle
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node_impl.hpp
Labels: in progress
