Repository ros2/rclcpp, pull requests merged in 2019-12, with the labels that each got.

#906 Use weak_ptr to store context in GraphListener
  rclcpp/include/rclcpp/graph_listener.hpp
  rclcpp/src/rclcpp/graph_listener.cpp
Labels: in review

#897 Removing "virtual", adding "override" keywords in the package
  rclcpp/include/rclcpp/executors/multi_threaded_executor.hpp
  rclcpp/include/rclcpp/executors/single_threaded_executor.hpp
  rclcpp/include/rclcpp/node_interfaces/node_base.hpp
  rclcpp/include/rclcpp/node_interfaces/node_clock.hpp
  rclcpp/include/rclcpp/node_interfaces/node_graph.hpp
  rclcpp/include/rclcpp/node_interfaces/node_logging.hpp
  rclcpp/include/rclcpp/node_interfaces/node_services.hpp
  rclcpp/include/rclcpp/node_interfaces/node_timers.hpp
  rclcpp/include/rclcpp/node_interfaces/node_waitables.hpp
  rclcpp/include/rclcpp/service.hpp
  rclcpp/include/rclcpp/strategies/allocator_memory_strategy.hpp
Labels: enhancement

#929 Use absolute topic name for parameter events
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
Labels: enhancement, in review

#935 [Dashing] backport rclcpp_components_register_node
  rclcpp_components/CMakeLists.txt
  rclcpp_components/cmake/rclcpp_components_register_node.cmake
  rclcpp_components/rclcpp_components-extras.cmake.in
  rclcpp_components/src/node_main.cpp.in
Labels: in review

#934 [dashing backport] Fixed "memory leak" in action clients (#920)
  rclcpp_action/src/client.cpp
Labels: in review

#922 Create node clock calls const (try 2)
  rclcpp/include/rclcpp/node.hpp
  rclcpp/include/rclcpp/node_interfaces/node_clock.hpp
  rclcpp/include/rclcpp/node_interfaces/node_clock_interface.hpp
  rclcpp/src/rclcpp/node.cpp
  rclcpp/src/rclcpp/node_interfaces/node_clock.cpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
  rclcpp_lifecycle/src/lifecycle_node.cpp
Labels: enhancement

#945 fix function docblock, check for unparsed arguments
  rclcpp_components/cmake/rclcpp_components_register_node.cmake
Labels: in review

#948 Remove absolute path from installed CMake code
  rclcpp_components/rclcpp_components-extras.cmake.in
Labels: bug

#954 Avoid possible UB in Clock jump callbacks
  rclcpp/include/rclcpp/clock.hpp
  rclcpp/src/rclcpp/clock.cpp
  rclcpp/src/rclcpp/time_source.cpp
  rclcpp/test/test_time.cpp
Labels: in review
