Repository ros2/rclcpp, pull requests merged in 2019-05, with the labels that each got.

#696 Fixup clock
  rclcpp/include/rclcpp/clock.hpp
  rclcpp/src/rclcpp/clock.cpp
Labels: in review

#712 Add rcl_node_get_fully_qualified_name (ros2/rcl#255)
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
Labels: in review

#698 [WIP / Re-Opened] Add functions to return formatted Node Name-Namespace strings
  rclcpp/include/rclcpp/node.hpp
  rclcpp/src/rclcpp/node_interfaces/node_graph.cpp
  rclcpp/test/test_node.cpp
  rclcpp_components/test/test_component_manager_api.cpp
Labels: in review

#711 API updates for rmw preallocation work
  rclcpp/include/rclcpp/publisher.hpp
  rclcpp/src/rclcpp/executor.cpp
Labels: in progress

#714 check for nullptr before publishing event
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
Labels: bug, in review

#710 Add return code to CancelGoal service response
  rclcpp_action/include/rclcpp_action/client.hpp
  rclcpp_action/src/server.cpp
  rclcpp_action/test/test_client.cpp
  rclcpp_action/test/test_server.cpp
Labels: in review

#695 Implement callbacks for liveliness and deadline QoS events
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/callback_group.hpp
  rclcpp/include/rclcpp/create_publisher.hpp
  rclcpp/include/rclcpp/create_subscription.hpp
  rclcpp/include/rclcpp/exceptions.hpp
  rclcpp/include/rclcpp/memory_strategy.hpp
  rclcpp/include/rclcpp/node.hpp
  rclcpp/include/rclcpp/node_impl.hpp
  rclcpp/include/rclcpp/node_interfaces/node_base.hpp
  rclcpp/include/rclcpp/node_interfaces/node_base_interface.hpp
  rclcpp/include/rclcpp/node_interfaces/node_topics.hpp
  rclcpp/include/rclcpp/node_interfaces/node_topics_interface.hpp
  rclcpp/include/rclcpp/parameter_client.hpp
  rclcpp/include/rclcpp/publisher.hpp
  rclcpp/include/rclcpp/publisher_base.hpp
  rclcpp/include/rclcpp/publisher_factory.hpp
  rclcpp/include/rclcpp/publisher_options.hpp
  rclcpp/include/rclcpp/qos_event.hpp
  rclcpp/include/rclcpp/strategies/allocator_memory_strategy.hpp
  rclcpp/include/rclcpp/subscription.hpp
  rclcpp/include/rclcpp/subscription_base.hpp
  rclcpp/include/rclcpp/subscription_factory.hpp
  rclcpp/include/rclcpp/subscription_options.hpp
  rclcpp/include/rclcpp/waitable.hpp
  rclcpp/src/rclcpp/executor.cpp
  rclcpp/src/rclcpp/graph_listener.cpp
  rclcpp/src/rclcpp/node.cpp
  rclcpp/src/rclcpp/node_interfaces/node_base.cpp
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
  rclcpp/src/rclcpp/node_interfaces/node_topics.cpp
  rclcpp/src/rclcpp/publisher_base.cpp
  rclcpp/src/rclcpp/qos_event.cpp
  rclcpp/src/rclcpp/subscription_base.cpp
  rclcpp/src/rclcpp/time_source.cpp
  rclcpp/src/rclcpp/waitable.cpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node_impl.hpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_publisher.hpp
Labels: in review

#709 Deprecate shared ptr publish
  rclcpp/include/rclcpp/publisher.hpp
  rclcpp/test/test_time_source.cpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_publisher.hpp
Labels: in review

#713 change API to encourage users to specify history depth always
  rclcpp/CMakeLists.txt
  rclcpp/cmake/rclcpp_add_build_failure_test.cmake
  rclcpp/include/rclcpp/allocator/allocator_common.hpp
  rclcpp/include/rclcpp/create_publisher.hpp
  rclcpp/include/rclcpp/create_subscription.hpp
  rclcpp/include/rclcpp/duration.hpp
  rclcpp/include/rclcpp/node.hpp
  rclcpp/include/rclcpp/node_impl.hpp
  rclcpp/include/rclcpp/node_interfaces/get_node_topics_interface.hpp
  rclcpp/include/rclcpp/node_interfaces/node_base.hpp
  rclcpp/include/rclcpp/node_interfaces/node_base_interface.hpp
  rclcpp/include/rclcpp/node_interfaces/node_parameters.hpp
  rclcpp/include/rclcpp/node_interfaces/node_topics.hpp
  rclcpp/include/rclcpp/node_interfaces/node_topics_interface.hpp
  rclcpp/include/rclcpp/node_options.hpp
  rclcpp/include/rclcpp/parameter_client.hpp
  rclcpp/include/rclcpp/publisher_factory.hpp
  rclcpp/include/rclcpp/publisher_options.hpp
  rclcpp/include/rclcpp/qos.hpp
  rclcpp/include/rclcpp/subscription_factory.hpp
  rclcpp/include/rclcpp/subscription_options.hpp
  rclcpp/include/rclcpp/subscription_traits.hpp
  rclcpp/src/rclcpp/duration.cpp
  rclcpp/src/rclcpp/node.cpp
  rclcpp/src/rclcpp/node_interfaces/node_base.cpp
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
  rclcpp/src/rclcpp/node_interfaces/node_topics.cpp
  rclcpp/src/rclcpp/node_options.cpp
  rclcpp/src/rclcpp/qos.cpp
  rclcpp/src/rclcpp/time_source.cpp
  rclcpp/test/node_interfaces/node_wrapper.hpp
  rclcpp/test/node_interfaces/test_does_not_compile/get_node_topics_interface_const_ptr_rclcpp_node.cpp
  rclcpp/test/node_interfaces/test_does_not_compile/get_node_topics_interface_const_ptr_wrapped_node.cpp
  rclcpp/test/node_interfaces/test_does_not_compile/get_node_topics_interface_const_ref_rclcpp_node.cpp
  rclcpp/test/node_interfaces/test_does_not_compile/get_node_topics_interface_const_ref_wrapped_node.cpp
  rclcpp/test/node_interfaces/test_get_node_interfaces.cpp
  rclcpp/test/test_duration.cpp
  rclcpp/test/test_pub_sub_option_interface.cpp
  rclcpp/test/test_publisher.cpp
  rclcpp/test/test_publisher_subscription_count_api.cpp
  rclcpp/test/test_serialized_message_allocator.cpp
  rclcpp/test/test_subscription.cpp
  rclcpp/test/test_subscription_publisher_count_api.cpp
  rclcpp/test/test_time_source.cpp
  rclcpp_action/CMakeLists.txt
  rclcpp_action/include/rclcpp_action/qos.hpp
  rclcpp_action/src/qos.cpp
  rclcpp_action/test/test_client.cpp
  rclcpp_action/test/test_server.cpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node_impl.hpp
  rclcpp_lifecycle/src/lifecycle_node.cpp
  rclcpp_lifecycle/test/test_lifecycle_node.cpp
Labels: in review

#719 Fix heap-use-after-free and memory leaks reported from test_node.cpp
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
  rclcpp/src/rclcpp/node_options.cpp
Labels: in progress

#707 Add missing template functionality to lifecycle_node.
  rclcpp/include/rclcpp/node.hpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node_impl.hpp
  rclcpp_lifecycle/src/lifecycle_node.cpp
Labels: in review

#718 Guard against ParameterNotDeclaredException in parameter service callbacks
  rclcpp/src/rclcpp/parameter_service.cpp
Labels: in review

#688 Created `on_parameter_event` static function
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/parameter_client.hpp
  rclcpp/src/rclcpp/time_source.cpp
  rclcpp/test/test_parameter_client.cpp
Labels: enhancement, in review

#723 fix clang warning
  rclcpp/test/test_intra_process_manager.cpp
Labels: in review

#729 Throw nice errors when creating a publisher with intraprocess communication and incompatible qos policy
  rclcpp/src/rclcpp/node_interfaces/node_topics.cpp
  rclcpp/src/rclcpp/publisher_base.cpp
  rclcpp/test/test_publisher.cpp
Labels: in review

#736 don't use global arguments for components loaded into the manager
  rclcpp_components/src/component_manager.cpp
Labels: bug, in review

#738 Guard against calling null goal response callback
  rclcpp_action/include/rclcpp_action/client.hpp
Labels: in progress

#741 ensure removal of guard conditions of expired nodes from memory strategy
  rclcpp/include/rclcpp/executor.hpp
  rclcpp/include/rclcpp/memory_strategy.hpp
  rclcpp/include/rclcpp/strategies/allocator_memory_strategy.hpp
  rclcpp/src/rclcpp/executor.cpp
  rclcpp/src/rclcpp/memory_strategy.cpp
  rclcpp/test/test_executor.cpp
  rclcpp/test/test_find_weak_nodes.cpp
Labels: bug, in review

#735 Enforce parameter ranges
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
  rclcpp/test/test_node.cpp
Labels: in review

#745 Rename parameter options
  rclcpp/include/rclcpp/node_interfaces/node_parameters.hpp
  rclcpp/include/rclcpp/node_interfaces/node_parameters_interface.hpp
  rclcpp/include/rclcpp/node_options.hpp
  rclcpp/src/rclcpp/node.cpp
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
  rclcpp/src/rclcpp/node_options.cpp
  rclcpp/test/test_node.cpp
  rclcpp_components/src/component_manager.cpp
  rclcpp_lifecycle/src/lifecycle_node.cpp
Labels: in review

#749 Avoid 'Intra process message no longer being stored when trying to ha…
  rclcpp/include/rclcpp/subscription.hpp
Labels: in review
