Repository ros2/rclcpp, pull requests merged in 2019-10, with the labels that each got.

#881 Fix Compiler Warning
  rclcpp/include/rclcpp/message_memory_strategy.hpp
Labels: enhancement, in review

#883 make get_actual_qos return a rclcpp::QoS
  rclcpp/include/rclcpp/publisher_base.hpp
  rclcpp/include/rclcpp/subscription_base.hpp
  rclcpp/src/rclcpp/publisher_base.cpp
  rclcpp/src/rclcpp/subscription_base.cpp
Labels: enhancement, in review

#882 add mechanism to pass rmw impl specific payloads during pub/sub creation
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/detail/rmw_implementation_specific_payload.hpp
  rclcpp/include/rclcpp/detail/rmw_implementation_specific_publisher_payload.hpp
  rclcpp/include/rclcpp/detail/rmw_implementation_specific_subscription_payload.hpp
  rclcpp/include/rclcpp/publisher.hpp
  rclcpp/include/rclcpp/publisher_options.hpp
  rclcpp/include/rclcpp/subscription.hpp
  rclcpp/include/rclcpp/subscription_options.hpp
  rclcpp/src/rclcpp/detail/rmw_implementation_specific_payload.cpp
  rclcpp/src/rclcpp/detail/rmw_implementation_specific_publisher_payload.cpp
  rclcpp/src/rclcpp/detail/rmw_implementation_specific_subscription_payload.cpp
Labels: enhancement, in review

#887 0.7.11
  rclcpp/CHANGELOG.rst
  rclcpp/package.xml
  rclcpp_action/CHANGELOG.rst
  rclcpp_action/package.xml
  rclcpp_components/CHANGELOG.rst
  rclcpp_components/package.xml
  rclcpp_lifecycle/CHANGELOG.rst
  rclcpp_lifecycle/package.xml
Labels: in review

#888 [rclcpp_action] Do not throw exception in action client if take fails
  rclcpp_action/src/client.cpp
Labels: in review

#853 Trait tests for generated actions
  rclcpp_action/CMakeLists.txt
  rclcpp_action/test/test_traits.cpp
Labels: enhancement

#894 Drop rclcpp remove_ros_arguments_null test case.
  rclcpp/test/test_utilities.cpp
Labels: enhancement

#864 Zero copy api
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/loaned_message.hpp
  rclcpp/include/rclcpp/publisher.hpp
  rclcpp/include/rclcpp/publisher_base.hpp
  rclcpp/include/rclcpp/subscription.hpp
  rclcpp/include/rclcpp/subscription_base.hpp
  rclcpp/src/rclcpp/executor.cpp
  rclcpp/src/rclcpp/publisher_base.cpp
  rclcpp/src/rclcpp/subscription_base.cpp
  rclcpp/test/test_loaned_message.cpp
Labels: enhancement

#778 New Intra-Process Communication
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/any_executable.hpp
  rclcpp/include/rclcpp/any_subscription_callback.hpp
  rclcpp/include/rclcpp/create_subscription.hpp
  rclcpp/include/rclcpp/detail/resolve_intra_process_buffer_type.hpp
  rclcpp/include/rclcpp/detail/resolve_use_intra_process.hpp
  rclcpp/include/rclcpp/executor.hpp
  rclcpp/include/rclcpp/experimental/README.md
  rclcpp/include/rclcpp/experimental/buffers/buffer_implementation_base.hpp
  rclcpp/include/rclcpp/experimental/buffers/intra_process_buffer.hpp
  rclcpp/include/rclcpp/experimental/buffers/ring_buffer_implementation.hpp
  rclcpp/include/rclcpp/experimental/create_intra_process_buffer.hpp
  rclcpp/include/rclcpp/experimental/intra_process_manager.hpp
  rclcpp/include/rclcpp/experimental/subscription_intra_process.hpp
  rclcpp/include/rclcpp/experimental/subscription_intra_process_base.hpp
  rclcpp/include/rclcpp/intra_process_buffer_type.hpp
  rclcpp/include/rclcpp/intra_process_manager.hpp
  rclcpp/include/rclcpp/intra_process_manager_impl.hpp
  rclcpp/include/rclcpp/loaned_message.hpp
  rclcpp/include/rclcpp/macros.hpp
  rclcpp/include/rclcpp/mapped_ring_buffer.hpp
  rclcpp/include/rclcpp/node_impl.hpp
  rclcpp/include/rclcpp/publisher.hpp
  rclcpp/include/rclcpp/publisher_base.hpp
  rclcpp/include/rclcpp/publisher_factory.hpp
  rclcpp/include/rclcpp/strategies/allocator_memory_strategy.hpp
  rclcpp/include/rclcpp/subscription.hpp
  rclcpp/include/rclcpp/subscription_base.hpp
  rclcpp/include/rclcpp/subscription_factory.hpp
  rclcpp/include/rclcpp/subscription_options.hpp
  rclcpp/src/rclcpp/any_executable.cpp
  rclcpp/src/rclcpp/executor.cpp
  rclcpp/src/rclcpp/intra_process_manager.cpp
  rclcpp/src/rclcpp/intra_process_manager_impl.cpp
  rclcpp/src/rclcpp/memory_strategy.cpp
  rclcpp/src/rclcpp/node_interfaces/node_topics.cpp
  rclcpp/src/rclcpp/publisher_base.cpp
  rclcpp/src/rclcpp/subscription_base.cpp
  rclcpp/src/rclcpp/subscription_intra_process_base.cpp
  rclcpp/src/rclcpp/time_source.cpp
  rclcpp/test/test_intra_process_buffer.cpp
  rclcpp/test/test_intra_process_manager.cpp
  rclcpp/test/test_mapped_ring_buffer.cpp
  rclcpp/test/test_publisher.cpp
  rclcpp/test/test_ring_buffer_implementation.cpp
  rclcpp/test/test_subscription.cpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node_impl.hpp
Labels: enhancement, in review

#879 Enable throttling logs
  rclcpp/include/rclcpp/clock.hpp
  rclcpp/resource/logging.hpp.em
  rclcpp/test/test_logging.cpp
Labels: enhancement, in progress
