Repository ros2/rclcpp, pull requests merged in 2019-04, with the labels that each got.

#667 Add function to get publisher actual qos settings
  rclcpp/include/rclcpp/publisher.hpp
  rclcpp/src/rclcpp/publisher.cpp
Labels: in progress

#681 use do { .. } while(0) around content of logging macros
  rclcpp/resource/logging.hpp.em
Labels: enhancement, in review

#674 Check QoS policy when configuring intraprocess, skip interprocess publish when possible
  rclcpp/include/rclcpp/node.hpp
  rclcpp/include/rclcpp/node_impl.hpp
  rclcpp/include/rclcpp/publisher.hpp
  rclcpp/src/rclcpp/publisher.cpp
  rclcpp/test/test_publisher.cpp
Labels: in review

#665 Introduce rclcpp_components to implement composition
  rclcpp/CMakeLists.txt
  rclcpp/cmake/rclcpp_create_node_main.cmake
  rclcpp_components/CMakeLists.txt
  rclcpp_components/cmake/rclcpp_components_package_hook.cmake
  rclcpp_components/cmake/rclcpp_components_register_nodes.cmake
  rclcpp_components/include/rclcpp_components/node_factory.hpp
  rclcpp_components/include/rclcpp_components/node_factory_template.hpp
  rclcpp_components/include/rclcpp_components/node_instance_wrapper.hpp
  rclcpp_components/include/rclcpp_components/register_node_macro.hpp
  rclcpp_components/package.xml
  rclcpp_components/rclcpp_components-extras.cmake
  rclcpp_components/src/component_container.cpp
  rclcpp_components/src/component_container_mt.cpp
  rclcpp_components/src/component_manager.cpp
  rclcpp_components/src/component_manager.hpp
  rclcpp_components/test/components/test_component.cpp
  rclcpp_components/test/test_component_manager.cpp
  rclcpp_components/test/test_component_manager_api.cpp
Labels: in review

#682 refactor SignalHandler logger to avoid race during destruction
  rclcpp/src/rclcpp/signal_handler.cpp
Labels: bug, in review

#671 Replace const char * with a std::array<char, TOPIC_NAME_LENGTH> as the key of IPM IDTopicMap
  rclcpp/include/rclcpp/intra_process_manager_impl.hpp
Labels: in review

#686 Backport #637 - Wait for action server before sending goal
  rclcpp_action/test/test_client.cpp
Labels: in review

#684 Replaced strncpy with memcpy
  rclcpp/include/rclcpp/intra_process_manager_impl.hpp
Labels: in review

#673 Options-struct interfaces for creating publishers/subscribers (pre-QoS, standalone)
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/intra_process_setting.hpp
  rclcpp/include/rclcpp/node.hpp
  rclcpp/include/rclcpp/node_impl.hpp
  rclcpp/include/rclcpp/publisher_options.hpp
  rclcpp/include/rclcpp/subscription_options.hpp
  rclcpp/test/test_pub_sub_option_interface.cpp
Labels: in progress

#680 logging, remove_const before comparison
  rclcpp/resource/logging.hpp.em
Labels: in review

#691 Update to be compatible with new rmw_qos_profile_t
  rclcpp/test/test_publisher.cpp
Labels: in review

#677 Rename action state transitions
  rclcpp_action/include/rclcpp_action/server.hpp
  rclcpp_action/include/rclcpp_action/server_goal_handle.hpp
  rclcpp_action/src/server_goal_handle.cpp
  rclcpp_action/test/test_server.cpp
Labels: in review

#678 [WIP] Exception Generator function for implementing "from_rcl_error"
  rclcpp/src/rclcpp/exceptions.cpp
Labels: in review

#700 overload for node interfaces
  rclcpp_action/include/rclcpp_action/create_client.hpp
  rclcpp_action/include/rclcpp_action/create_server.hpp
Labels: in review

#697 Add method to read timer cancellation
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/timer.hpp
  rclcpp/src/rclcpp/timer.cpp
  rclcpp/test/test_timer.cpp
Labels: in progress

#692 Fixup utilities
  rclcpp/include/rclcpp/utilities.hpp
  rclcpp/src/rclcpp/utilities.cpp
Labels: in review

#703 Fix a concurrency problem in the multithreaded executor
  rclcpp/src/rclcpp/executors/multi_threaded_executor.cpp
Labels: in review

#495 Read only parameters
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/exceptions.hpp
  rclcpp/include/rclcpp/node.hpp
  rclcpp/include/rclcpp/node_impl.hpp
  rclcpp/include/rclcpp/node_interfaces/node_parameters.hpp
  rclcpp/include/rclcpp/node_interfaces/node_parameters_interface.hpp
  rclcpp/include/rclcpp/node_options.hpp
  rclcpp/include/rclcpp/parameter.hpp
  rclcpp/include/rclcpp/parameter_service.hpp
  rclcpp/include/rclcpp/parameter_value.hpp
  rclcpp/src/rclcpp/node.cpp
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
  rclcpp/src/rclcpp/node_options.cpp
  rclcpp/src/rclcpp/parameter.cpp
  rclcpp/src/rclcpp/parameter_value.cpp
  rclcpp/src/rclcpp/time_source.cpp
  rclcpp/test/test_local_parameters.cpp
  rclcpp/test/test_node.cpp
  rclcpp/test/test_node_initial_parameters.cpp
  rclcpp/test/test_time_source.cpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node_impl.hpp
  rclcpp_lifecycle/src/lifecycle_node.cpp
Labels: enhancement, in review

#690 New IntraProcessManager capable of storing shared_ptr<const T>
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/any_subscription_callback.hpp
  rclcpp/include/rclcpp/intra_process_manager.hpp
  rclcpp/include/rclcpp/intra_process_manager_impl.hpp
  rclcpp/include/rclcpp/mapped_ring_buffer.hpp
  rclcpp/include/rclcpp/publisher.hpp
  rclcpp/include/rclcpp/publisher_base.hpp
  rclcpp/include/rclcpp/publisher_factory.hpp
  rclcpp/include/rclcpp/subscription.hpp
  rclcpp/include/rclcpp/subscription_base.hpp
  rclcpp/include/rclcpp/subscription_factory.hpp
  rclcpp/src/rclcpp/intra_process_manager.cpp
  rclcpp/src/rclcpp/node_interfaces/node_topics.cpp
  rclcpp/src/rclcpp/publisher_base.cpp
  rclcpp/src/rclcpp/subscription_base.cpp
  rclcpp/test/test_intra_process_manager.cpp
  rclcpp/test/test_mapped_ring_buffer.cpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_publisher.hpp
Labels: in review

#708 Add assignment of parameter-related fields in node options constructor
  rclcpp/src/rclcpp/node_options.cpp
Labels: in review
