Repository ros2/rclcpp, pull requests merged in 2019-07, with the labels that each got.

#788 Add free function for creating service clients
  rclcpp/include/rclcpp/create_client.hpp
  rclcpp/include/rclcpp/node_impl.hpp
  rclcpp/test/test_client.cpp
Labels: in review

#772 Allow registering multiple on_parameters_set_callback
  rclcpp/include/rclcpp/node.hpp
  rclcpp/include/rclcpp/node_interfaces/node_parameters.hpp
  rclcpp/include/rclcpp/node_interfaces/node_parameters_interface.hpp
  rclcpp/src/rclcpp/node.cpp
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
  rclcpp/test/test_node.cpp
Labels: enhancement, in review

#793 Remove non-package from ament_target_dependencies()
  rclcpp_components/CMakeLists.txt
Labels: bug

#801 [dashing-backport] Add default value to options in LifecycleNode construnctor. Update API documentation. (#775)
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
Labels: enhancement, in review

#804 [Backport] Fix a comparison with a sign mismatch
  rclcpp/src/rclcpp/node_options.cpp
Labels: in review

#805 [Backport] Use params from node '/**' from parameter YAML file
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
Labels: in review
