Repository ros2/rclcpp, pull requests merged in 2019-11, with the labels that each got.

#926 add support for STREAM logging macros
  rclcpp/resource/logging.hpp.em
  rclcpp/test/test_logging.cpp
Labels: enhancement, in review

#891 [dashing backport] Do not throw exception in action client if take fails
  rclcpp_action/src/client.cpp
Labels: in review

#850 Bug fix on shutdown_on_sigint (not set on InitOptions constructors) to implement a custom interrupt signal handler
  rclcpp/src/rclcpp/init_options.cpp
Labels: enhancement, requires-changes

#920 issue-919 Fixed "memory leak" in action clients
  rclcpp_action/src/client.cpp
Labels: in review

#748 Add addition/subtraction assignment operators to Time
  rclcpp/include/rclcpp/time.hpp
  rclcpp/src/rclcpp/time.cpp
  rclcpp/test/test_time.cpp
Labels: enhancement

#844 Make Executor::spin_some() only check for work once
  rclcpp/src/rclcpp/executor.cpp
Labels: enhancement, in review

#914 Intra-process subscriber should use RMW actual qos. (ros2#913)
  rclcpp/include/rclcpp/subscription.hpp
  rclcpp/test/test_subscription.cpp
Labels: in review

#905 [crystal_backport] Do not throw exception in action client if take fails
  rclcpp_action/src/client.cpp
Labels: in review

#928 Correct published event message when declaring a parameter
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
Labels: bug, in review
