Repository ros2/rclcpp, pull requests merged in 2019-02, with the labels that each got.

#626 remove dependency on rclpy from rclcpp_lifecycle
  rclcpp_lifecycle/package.xml
Labels: enhancement, in review

#622 Replace node constructor arguments with NodeOptions
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/node.hpp
  rclcpp/include/rclcpp/node_interfaces/node_base.hpp
  rclcpp/include/rclcpp/node_options.hpp
  rclcpp/src/rclcpp/node.cpp
  rclcpp/src/rclcpp/node_interfaces/node_base.cpp
  rclcpp/src/rclcpp/node_options.cpp
  rclcpp/test/test_node_global_args.cpp
  rclcpp/test/test_node_initial_parameters.cpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
  rclcpp_lifecycle/src/lifecycle_node.cpp
Labels: in review

#614 Set Parameter Event Publisher settings #591
  rclcpp/include/rclcpp/node_interfaces/node_parameters.hpp
  rclcpp/include/rclcpp/node_options.hpp
  rclcpp/src/rclcpp/node.cpp
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
  rclcpp/src/rclcpp/node_options.cpp
  rclcpp_lifecycle/src/lifecycle_node.cpp
Labels: in review

#630 Replace 'auto' to 'const auto &'
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
Labels: in review

#581 Sub Node alternative
  rclcpp/include/rclcpp/node.hpp
  rclcpp/include/rclcpp/node_impl.hpp
  rclcpp/src/rclcpp/node.cpp
  rclcpp/test/test_client.cpp
  rclcpp/test/test_node.cpp
  rclcpp/test/test_publisher.cpp
  rclcpp/test/test_service.cpp
  rclcpp/test/test_subscription.cpp
Labels: in review

#628 Added count matching api and intra-process subscriber count
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/intra_process_manager.hpp
  rclcpp/include/rclcpp/intra_process_manager_impl.hpp
  rclcpp/include/rclcpp/publisher.hpp
  rclcpp/include/rclcpp/subscription.hpp
  rclcpp/include/rclcpp/subscription_factory.hpp
  rclcpp/src/rclcpp/intra_process_manager.cpp
  rclcpp/src/rclcpp/node_interfaces/node_topics.cpp
  rclcpp/src/rclcpp/publisher.cpp
  rclcpp/src/rclcpp/subscription.cpp
  rclcpp/test/test_publisher_subscription_count_api.cpp
  rclcpp/test/test_subscription_publisher_count_api.cpp
Labels: in review

#637 Wait for action server before sending goal
  rclcpp_action/test/test_client.cpp
Labels: bug, in review
