Repository ros2/rclcpp, pull requests merged in 2020-05, with the labels that each got.

#1101 Use RCL_RET_SERVICE_TAKE_FAILED and not RCL_RET_CLIENT_TAKE_FAILED when checking a request take
  rclcpp/src/rclcpp/service.cpp
Labels: bug, in review

#1100 Added Quality declaration: rclcpp, rclpp_action, rclcpp_components andrclcpp_lifecycle
  README.md
  rclcpp/QUALITY_DECLARATION.md
  rclcpp/README.md
  rclcpp_action/QUALITY_DECLARATION.md
  rclcpp_action/README.md
  rclcpp_components/QUALITY_DECLARATION.md
  rclcpp_components/README.md
  rclcpp_lifecycle/QUALITY_DECLARATION.md
  rclcpp_lifecycle/README.md
Labels: documentation

#1103 Added docblock in rclcpp
  rclcpp/include/rclcpp/client.hpp
  rclcpp/include/rclcpp/clock.hpp
  rclcpp/include/rclcpp/duration.hpp
  rclcpp/include/rclcpp/node.hpp
  rclcpp/include/rclcpp/parameter.hpp
  rclcpp/include/rclcpp/publisher.hpp
  rclcpp/include/rclcpp/qos.hpp
  rclcpp/include/rclcpp/rclcpp.hpp
  rclcpp/include/rclcpp/service.hpp
  rclcpp/include/rclcpp/subscription.hpp
  rclcpp/include/rclcpp/subscription_options.hpp
  rclcpp/include/rclcpp/time.hpp
  rclcpp/include/rclcpp/time_source.hpp
  rclcpp/include/rclcpp/timer.hpp
Labels: documentation, enhancement

#1089 Added rclcpp lifecycle Doxyfile
  rclcpp_lifecycle/Doxyfile
Labels: documentation, enhancement

#1107 Remove MANUAL_BY_NODE liveliness API
  rclcpp/include/rclcpp/node.hpp
  rclcpp/include/rclcpp/node_interfaces/node_base.hpp
  rclcpp/include/rclcpp/node_interfaces/node_base_interface.hpp
  rclcpp/src/rclcpp/node.cpp
  rclcpp/src/rclcpp/node_interfaces/node_base.cpp
  rclcpp/test/test_node.cpp
  rclcpp/test/test_qos.cpp
Labels: in review

#1102 Added dockblock to ComponentManager class
  rclcpp_components/include/rclcpp_components/component_manager.hpp
Labels: documentation, enhancement

#1116 [Quality Declaration] Fixed rep links and added more details to dependencies
  rclcpp/QUALITY_DECLARATION.md
  rclcpp_action/QUALITY_DECLARATION.md
  rclcpp_components/QUALITY_DECLARATION.md
  rclcpp_lifecycle/QUALITY_DECLARATION.md
Labels: documentation

#1105 Make test multi threaded executor more reliable
  rclcpp/CMakeLists.txt
  rclcpp/test/executors/test_multi_threaded_executor.cpp
Labels: bug, in review

#1106 Added features to rclcpp packages
  rclcpp/README.md
  rclcpp_action/README.md
  rclcpp_components/README.md
  rclcpp_components/include/rclcpp_components/component_manager.hpp
  rclcpp_lifecycle/README.md
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/state.hpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/transition.hpp
Labels: documentation

#1031 [rclcpp] API review March 2020
  rclcpp/doc/api_review_march_2020.md
Labels: documentation

#1125 Fix thread safety issues related to logging
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/context.hpp
  rclcpp/src/rclcpp/context.cpp
  rclcpp/src/rclcpp/logging_mutex.cpp
  rclcpp/src/rclcpp/logging_mutex.hpp
  rclcpp/src/rclcpp/node_interfaces/node_base.cpp
Labels: in review

#1131 expose get_service_names_and_types_by_node from rcl in rclcpp
  rclcpp/include/rclcpp/node.hpp
  rclcpp/include/rclcpp/node_interfaces/node_graph.hpp
  rclcpp/include/rclcpp/node_interfaces/node_graph_interface.hpp
  rclcpp/src/rclcpp/node.cpp
  rclcpp/src/rclcpp/node_interfaces/node_graph.cpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
  rclcpp_lifecycle/src/lifecycle_node.cpp
Labels: enhancement

#1134 add add_on and remove_on fn to deprecate set_on_param fn
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
  rclcpp_lifecycle/src/lifecycle_node.cpp
Labels: in review

#1123 Deprecate set_on_parameters_set_callback
  rclcpp/include/rclcpp/node.hpp
  rclcpp/include/rclcpp/node_interfaces/node_parameters.hpp
  rclcpp/include/rclcpp/node_interfaces/node_parameters_interface.hpp
  rclcpp/src/rclcpp/node.cpp
  rclcpp/test/test_node.cpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
  rclcpp_lifecycle/src/lifecycle_node.cpp
  rclcpp_lifecycle/test/test_lifecycle_node.cpp
Labels: in review

#1132 Fix potential Construction/Destruction order problem between global contexts vector and Context of static lifetime
  rclcpp/include/rclcpp/context.hpp
  rclcpp/src/rclcpp/context.cpp
Labels: enhancement

#1136 Fix test_lifecycle_node.cpp:check_parameters
  rclcpp_lifecycle/test/test_lifecycle_node.cpp
Labels: bug, in review

#1135 Fix lock-order-inversion (potential deadlock)
  rclcpp/src/rclcpp/node_interfaces/node_graph.cpp
Labels: in review

#1127 Improved rclcpp docblock
  rclcpp/include/rclcpp/client.hpp
  rclcpp/include/rclcpp/context.hpp
  rclcpp/include/rclcpp/event.hpp
  rclcpp/include/rclcpp/executor.hpp
  rclcpp/include/rclcpp/executors/multi_threaded_executor.hpp
  rclcpp/include/rclcpp/executors/single_threaded_executor.hpp
  rclcpp/include/rclcpp/executors/static_executor_entities_collector.hpp
  rclcpp/include/rclcpp/executors/static_single_threaded_executor.hpp
  rclcpp/include/rclcpp/expand_topic_or_service_name.hpp
  rclcpp/include/rclcpp/graph_listener.hpp
  rclcpp/include/rclcpp/init_options.hpp
  rclcpp/include/rclcpp/loaned_message.hpp
  rclcpp/include/rclcpp/memory_strategies.hpp
  rclcpp/include/rclcpp/message_info.hpp
  rclcpp/include/rclcpp/node.hpp
  rclcpp/include/rclcpp/node_options.hpp
  rclcpp/include/rclcpp/parameter_client.hpp
  rclcpp/include/rclcpp/service.hpp
  rclcpp/include/rclcpp/subscription.hpp
  rclcpp/include/rclcpp/subscription_base.hpp
  rclcpp/include/rclcpp/subscription_factory.hpp
  rclcpp/include/rclcpp/time.hpp
  rclcpp/include/rclcpp/time_source.hpp
  rclcpp/include/rclcpp/timer.hpp
  rclcpp/include/rclcpp/topic_statistics/subscription_topic_statistics.hpp
  rclcpp/include/rclcpp/utilities.hpp
  rclcpp/include/rclcpp/wait_result.hpp
  rclcpp/include/rclcpp/wait_set_template.hpp
Labels: documentation

#1140 `SubscriptionBase::get_subscription_handle() const` should return a shared pointer to const value
  rclcpp/include/rclcpp/subscription_base.hpp
  rclcpp/src/rclcpp/subscription_base.cpp
Labels: bug

#1141 Pass shared pointer by value instead than by const & when possible
  rclcpp/include/rclcpp/wait_set_policies/dynamic_storage.hpp
  rclcpp/include/rclcpp/wait_set_policies/static_storage.hpp
Labels: enhancement, in review
