Repository ros2/rclcpp, pull requests merged in 2020-08, with the labels that each got.

#1256 increase test timeout necessary for Connext
  rclcpp_action/CMakeLists.txt
Labels: bug

#1257 Use global namespace for parameter events subscription topic
  rclcpp/include/rclcpp/parameter_client.hpp
Labels: bug

#1249 Make parameter clients use template constructors
  rclcpp/include/rclcpp/parameter_client.hpp
  rclcpp/src/rclcpp/parameter_client.cpp
Labels: enhancement

#1271 add get_domain_id method to rclcpp::Context.
  rclcpp/include/rclcpp/context.hpp
  rclcpp/src/rclcpp/context.cpp
Labels: enhancement

#1240 Added missing tests for rclcpp lifecycle
  rclcpp_lifecycle/test/test_lifecycle_service_client.cpp
Labels: enhancement

#1274 fix topic stats test, wait for more messages, only check the ones with samples
  rclcpp/test/rclcpp/topic_statistics/test_subscription_topic_statistics.cpp
Labels: bug

#1278 (foxy) Add operator!= to Duration
  rclcpp/include/rclcpp/duration.hpp
  rclcpp/src/rclcpp/duration.cpp
  rclcpp/test/test_duration.cpp
Labels: in review
