Repository ros2/rclcpp, pull requests merged in 2020-09, with the labels that each got.

#1218 Adding callback groups in executor
  rclcpp/include/rclcpp/callback_group.hpp
  rclcpp/include/rclcpp/executor.hpp
  rclcpp/include/rclcpp/executors/static_executor_entities_collector.hpp
  rclcpp/include/rclcpp/executors/static_single_threaded_executor.hpp
  rclcpp/include/rclcpp/memory_strategy.hpp
  rclcpp/include/rclcpp/node.hpp
  rclcpp/include/rclcpp/node_interfaces/node_base.hpp
  rclcpp/include/rclcpp/node_interfaces/node_base_interface.hpp
  rclcpp/include/rclcpp/strategies/allocator_memory_strategy.hpp
  rclcpp/src/rclcpp/callback_group.cpp
  rclcpp/src/rclcpp/executor.cpp
  rclcpp/src/rclcpp/executors/static_executor_entities_collector.cpp
  rclcpp/src/rclcpp/executors/static_single_threaded_executor.cpp
  rclcpp/src/rclcpp/memory_strategy.cpp
  rclcpp/src/rclcpp/node.cpp
  rclcpp/src/rclcpp/node_interfaces/node_base.cpp
  rclcpp/test/CMakeLists.txt
  rclcpp/test/rclcpp/strategies/test_allocator_memory_strategy.cpp
  rclcpp/test/rclcpp/test_add_callback_groups_to_executor.cpp
  rclcpp/test/rclcpp/test_find_weak_nodes.cpp
  rclcpp/test/rclcpp/test_memory_strategy.cpp
Labels: enhancement

#1310 Replace std_msgs with test_msgs in executors test
  rclcpp/test/CMakeLists.txt
  rclcpp/test/rclcpp/executors/test_executors.cpp
Labels: bug

#1312 Use best effort, keep last, history depth 1 QoS Profile for '/clock' subscriptions
  rclcpp/src/rclcpp/time_source.cpp
Labels: enhancement

#1358 Improved test_subscription_options
  rclcpp/test/rclcpp/test_subscription_options.cpp
Labels: tests

#1359 Covered resolve_use_intra_process
  rclcpp/test/rclcpp/test_subscription.cpp
Labels: tests

#1360 Improved test publisher - zero qos history depth value exception
  rclcpp/test/rclcpp/test_publisher.cpp
Labels: tests
