Repository ros2/rclcpp, pull requests merged in 2020-11, with the labels that each got.

#1415 Avoid parsing arguments twice
  rclcpp/src/rclcpp/utilities.cpp
  rclcpp/test/rclcpp/test_utilities.cpp
Labels: enhancement

#1432 rclcpp::Duration constructors might be confusing to users migrating from ROS 1
  rclcpp/include/rclcpp/duration.hpp
  rclcpp/src/rclcpp/duration.cpp
  rclcpp/src/rclcpp/time.cpp
  rclcpp/test/rclcpp/test_duration.cpp
  rclcpp/test/rclcpp/test_time.cpp
Labels: enhancement

#1413 Added executor benchmark tests
  rclcpp/test/benchmark/CMakeLists.txt
  rclcpp/test/benchmark/benchmark_executor.cpp
Labels: tests

#1444 Add benchmarks for parameter interface
  rclcpp/test/benchmark/CMakeLists.txt
  rclcpp/test/benchmark/benchmark_node_parameters_interface.cpp
Labels: in review, tests

#1408 Qos configurability
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/create_publisher.hpp
  rclcpp/include/rclcpp/create_subscription.hpp
  rclcpp/include/rclcpp/detail/qos_parameters.hpp
  rclcpp/include/rclcpp/exceptions/exceptions.hpp
  rclcpp/include/rclcpp/publisher_options.hpp
  rclcpp/include/rclcpp/qos_overriding_options.hpp
  rclcpp/include/rclcpp/subscription_options.hpp
  rclcpp/src/rclcpp/node_interfaces/node_base.cpp
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
  rclcpp/src/rclcpp/qos_overriding_options.cpp
  rclcpp/test/rclcpp/CMakeLists.txt
  rclcpp/test/rclcpp/test_create_subscription.cpp
  rclcpp/test/rclcpp/test_publisher.cpp
  rclcpp/test/rclcpp/test_qos_overriding_options.cpp
  rclcpp/test/rclcpp/test_qos_parameters.cpp
Labels: enhancement

#1459 Revert "Qos configurability (#1408)"
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/create_publisher.hpp
  rclcpp/include/rclcpp/create_subscription.hpp
  rclcpp/include/rclcpp/detail/qos_parameters.hpp
  rclcpp/include/rclcpp/exceptions/exceptions.hpp
  rclcpp/include/rclcpp/publisher_options.hpp
  rclcpp/include/rclcpp/qos_overriding_options.hpp
  rclcpp/include/rclcpp/subscription_options.hpp
  rclcpp/src/rclcpp/node_interfaces/node_base.cpp
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
  rclcpp/src/rclcpp/qos_overriding_options.cpp
  rclcpp/test/rclcpp/CMakeLists.txt
  rclcpp/test/rclcpp/test_create_subscription.cpp
  rclcpp/test/rclcpp/test_publisher.cpp
  rclcpp/test/rclcpp/test_qos_overriding_options.cpp
  rclcpp/test/rclcpp/test_qos_parameters.cpp
Labels: enhancement

#1241 Add `take_data` to `Waitable` and `data` to `AnyExecutable`
  rclcpp/include/rclcpp/any_executable.hpp
  rclcpp/include/rclcpp/executors/static_executor_entities_collector.hpp
  rclcpp/include/rclcpp/experimental/subscription_intra_process.hpp
  rclcpp/include/rclcpp/experimental/subscription_intra_process_base.hpp
  rclcpp/include/rclcpp/qos_event.hpp
  rclcpp/include/rclcpp/waitable.hpp
  rclcpp/src/rclcpp/executor.cpp
  rclcpp/src/rclcpp/executors/static_executor_entities_collector.cpp
  rclcpp/src/rclcpp/executors/static_single_threaded_executor.cpp
  rclcpp/test/benchmark/benchmark_executor.cpp
  rclcpp/test/rclcpp/executors/test_executors.cpp
  rclcpp/test/rclcpp/executors/test_static_executor_entities_collector.cpp
  rclcpp/test/rclcpp/node_interfaces/test_node_waitables.cpp
  rclcpp/test/rclcpp/strategies/test_allocator_memory_strategy.cpp
  rclcpp/test/rclcpp/test_memory_strategy.cpp
  rclcpp/test/rclcpp/test_publisher.cpp
  rclcpp/test/rclcpp/test_qos_event.cpp
  rclcpp/test/rclcpp/wait_set_policies/test_dynamic_storage.cpp
  rclcpp/test/rclcpp/wait_set_policies/test_static_storage.cpp
  rclcpp/test/rclcpp/wait_set_policies/test_storage_policy_common.cpp
  rclcpp/test/rclcpp/wait_set_policies/test_thread_safe_synchronization.cpp
  rclcpp_action/include/rclcpp_action/client.hpp
  rclcpp_action/include/rclcpp_action/server.hpp
  rclcpp_action/src/client.cpp
  rclcpp_action/src/server.cpp
Labels: bug

#1465 Qos configurability (take 2)
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/create_publisher.hpp
  rclcpp/include/rclcpp/create_subscription.hpp
  rclcpp/include/rclcpp/detail/qos_parameters.hpp
  rclcpp/include/rclcpp/exceptions/exceptions.hpp
  rclcpp/include/rclcpp/publisher_options.hpp
  rclcpp/include/rclcpp/qos_overriding_options.hpp
  rclcpp/include/rclcpp/subscription_options.hpp
  rclcpp/src/rclcpp/node_interfaces/node_base.cpp
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
  rclcpp/src/rclcpp/qos_overriding_options.cpp
  rclcpp/test/rclcpp/CMakeLists.txt
  rclcpp/test/rclcpp/test_create_subscription.cpp
  rclcpp/test/rclcpp/test_publisher.cpp
  rclcpp/test/rclcpp/test_qos_overriding_options.cpp
  rclcpp/test/rclcpp/test_qos_parameters.cpp
Labels: enhancement

#1463 Add performance tests for parameter transport
  rclcpp/test/benchmark/CMakeLists.txt
  rclcpp/test/benchmark/benchmark_parameter_client.cpp
Labels: enhancement

#1476 Add benchmarks for components
  rclcpp_components/CMakeLists.txt
  rclcpp_components/package.xml
  rclcpp_components/test/benchmark/benchmark_components.cpp
Labels: in review, tests

#1479 [foxy] Add benchmarks for components
  rclcpp_components/CMakeLists.txt
  rclcpp_components/package.xml
  rclcpp_components/test/benchmark/benchmark_components.cpp
Labels: in review, tests
