Repository ros2/rclcpp, pull requests merged in 2020-04, with the labels that each got.

#924 Support for ON_REQUESTED_INCOMPATIBLE_QOS and ON_OFFERED_INCOMPATIBLE_QOS events
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/publisher.hpp
  rclcpp/include/rclcpp/qos_event.hpp
  rclcpp/include/rclcpp/subscription.hpp
  rclcpp/src/rclcpp/qos_event.cpp
  rclcpp/test/test_qos_event.cpp
Labels: in review

#1014 Changed rosidl_generator_c/cpp to rosidl_runtime_c/cpp
  rclcpp/CMakeLists.txt
  rclcpp/package.xml
  rclcpp_action/CMakeLists.txt
  rclcpp_action/package.xml
Labels: enhancement

#998 Ensure logging is initialized just once
  rclcpp/include/rclcpp/context.hpp
  rclcpp/include/rclcpp/init_options.hpp
  rclcpp/src/rclcpp/context.cpp
  rclcpp/src/rclcpp/init_options.cpp
Labels: in review

#1091 Added rclcpp_components Doxyfile
  rclcpp_components/Doxyfile
Labels: documentation, enhancement
