Repository ros2/rclcpp, pull requests merged in 2020-07, with the labels that each got.

#1205 Remove usage of domain id in node options
  rclcpp/include/rclcpp/node_options.hpp
  rclcpp/src/rclcpp/node_options.cpp
Labels: enhancement, in review

#1210 link against thread library where necessary
  rclcpp/CMakeLists.txt
Labels: bug

#1214 [backport foxy] link against thread library where necessary
  rclcpp/CMakeLists.txt
Labels: bug

#1208 [Backport Dashing]Fixed doxygen warnings (#1163)
  rclcpp/include/rclcpp/clock.hpp
  rclcpp/include/rclcpp/executors/multi_threaded_executor.hpp
  rclcpp/include/rclcpp/node.hpp
  rclcpp/include/rclcpp/parameter_client.hpp
  rclcpp/include/rclcpp/service.hpp
  rclcpp/include/rclcpp/subscription_factory.hpp
  rclcpp/include/rclcpp/time.hpp
  rclcpp/include/rclcpp/timer.hpp
  rclcpp/include/rclcpp/waitable.hpp
  rclcpp_action/include/rclcpp_action/create_client.hpp
  rclcpp_action/include/rclcpp_action/create_server.hpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
Labels: documentation

#1213 Make ring buffer thread-safe
  rclcpp/include/rclcpp/experimental/buffers/ring_buffer_implementation.hpp
Labels: bug

#1245 fix node graph test with Connext and CycloneDDS returning actual data
  rclcpp/test/rclcpp/node_interfaces/test_node_graph.cpp
Labels: bug

#1246 fix failing test with Connext since it doesn't wait for discovery
  rclcpp/test/rclcpp/node_interfaces/test_node_graph.cpp
Labels: bug
