Repository ros2/rclcpp, pull requests merged in 2020-06, with the labels that each got.

#1146 Make test_rate more reliable on Windows and improve error output when it fails
  rclcpp/test/test_rate.cpp
Labels: enhancement, in review

#1149 Add missing virtual destructors
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/rate.hpp
  rclcpp/include/rclcpp/timer.hpp
  rclcpp_action/CMakeLists.txt
  rclcpp_components/CMakeLists.txt
  rclcpp_lifecycle/CMakeLists.txt
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_publisher.hpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/node_interfaces/lifecycle_node_interface.hpp
Labels: bug, in review

#1113 Allow spin_until_future_complete to accept std::future
  rclcpp/include/rclcpp/executor.hpp
  rclcpp/include/rclcpp/executors.hpp
  rclcpp/include/rclcpp/executors/static_single_threaded_executor.hpp
  rclcpp/test/test_executor.cpp
Labels: enhancement, in review

#1023 Fix spin_until_future_complete: check spinning value
  rclcpp/include/rclcpp/executor.hpp
  rclcpp/src/rclcpp/executor.cpp
Labels: in review

#1167 Check if context is valid when looping in spin_some
  rclcpp/src/rclcpp/executor.cpp
Labels: in review

#1156 Add spin_all method to Executor
  rclcpp/include/rclcpp/executor.hpp
  rclcpp/src/rclcpp/executor.cpp
  rclcpp/test/rclcpp/test_executor.cpp
Labels: bug, in review

#1164 Add message lost subscription event
  rclcpp/include/rclcpp/qos_event.hpp
  rclcpp/include/rclcpp/subscription.hpp
Labels: in review

#1191 [Foxy backport] Fixed doxygen warnings (#1163)
  rclcpp/include/rclcpp/clock.hpp
  rclcpp/include/rclcpp/executors/multi_threaded_executor.hpp
  rclcpp/include/rclcpp/node.hpp
  rclcpp/include/rclcpp/parameter_client.hpp
  rclcpp/include/rclcpp/serialization.hpp
  rclcpp/include/rclcpp/service.hpp
  rclcpp/include/rclcpp/subscription_factory.hpp
  rclcpp/include/rclcpp/time.hpp
  rclcpp/include/rclcpp/timer.hpp
  rclcpp/include/rclcpp/topic_statistics/subscription_topic_statistics.hpp
  rclcpp/include/rclcpp/wait_set_template.hpp
  rclcpp/include/rclcpp/waitable.hpp
  rclcpp_action/include/rclcpp_action/create_client.hpp
  rclcpp_action/include/rclcpp_action/create_server.hpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
Labels: documentation

#1201 [Backport Dashing] Added rclcpp_components Doxyfile (#1091)
  rclcpp_components/Doxyfile
Labels: documentation

#1200 [Backport Eloquent] Added rclcpp_components Doxyfile (#1091)
  rclcpp_components/Doxyfile
Labels: documentation

#1204 fix race in test_lifecycle_service_client
  rclcpp_lifecycle/test/test_lifecycle_service_client.cpp
Labels: bug

#1158 Bump to QD to level 3 and fixed links
  rclcpp/QUALITY_DECLARATION.md
  rclcpp/README.md
  rclcpp_action/QUALITY_DECLARATION.md
  rclcpp_action/README.md
  rclcpp_components/QUALITY_DECLARATION.md
  rclcpp_components/README.md
  rclcpp_lifecycle/QUALITY_DECLARATION.md
  rclcpp_lifecycle/README.md
Labels: enhancement

#1199 remove deprecated set_on_parameters_set_callback function
  rclcpp/include/rclcpp/node.hpp
  rclcpp/include/rclcpp/node_interfaces/node_parameters.hpp
  rclcpp/include/rclcpp/node_interfaces/node_parameters_interface.hpp
  rclcpp/src/rclcpp/node.cpp
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
  rclcpp/test/rclcpp/test_node.cpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
  rclcpp_lifecycle/src/lifecycle_node.cpp
Labels: in review
