Repository ros2/rclcpp, pull requests merged in 2021-01, with the labels that each got.

#1508 Better documentation for the QoS class
  rclcpp/include/rclcpp/qos.hpp
Labels: requires-changes

#1509 Add get_logging_directory method to rclcpp::Logger
  rclcpp/include/rclcpp/logger.hpp
  rclcpp/src/rclcpp/logger.cpp
  rclcpp/test/rclcpp/test_logger.cpp
Labels: enhancement

#1511 Revert "Add get_logging_directory method to rclcpp::Logger (#1509)"
  rclcpp/include/rclcpp/logger.hpp
  rclcpp/src/rclcpp/logger.cpp
  rclcpp/test/rclcpp/test_logger.cpp
Labels: bug

#1513 Reapply "Add get_logging_directory method to rclcpp::Logger (#1509)"
  rclcpp/include/rclcpp/logger.hpp
  rclcpp/src/rclcpp/logger.cpp
  rclcpp/test/rclcpp/test_logger.cpp
Labels: enhancement

#1505 Allow to add/remove nodes thread safely in rclcpp::Executor
  rclcpp/include/rclcpp/executor.hpp
  rclcpp/src/rclcpp/executor.cpp
  rclcpp/test/rclcpp/test_executor.cpp
Labels: bug

#1512 Allow reconfiguring 'clock' topic qos
  rclcpp/include/rclcpp/time_source.hpp
  rclcpp/src/rclcpp/time_source.cpp
Labels: enhancement

#1520 Fix error when using IPC with StaticSingleThreadExecutor
  rclcpp/src/rclcpp/executors/static_executor_entities_collector.cpp
  rclcpp/src/rclcpp/executors/static_single_threaded_executor.cpp
Labels: bug

#1527 Fix #1526.
  rclcpp_action/src/server.cpp
Labels: bug
