Repository ros2/rclcpp, pull requests merged in 2021-05, with the labels that each got.

#1557 [rclcpp] Type Adaptation feature
  rclcpp/include/rclcpp/any_subscription_callback.hpp
  rclcpp/include/rclcpp/create_subscription.hpp
  rclcpp/include/rclcpp/experimental/intra_process_manager.hpp
  rclcpp/include/rclcpp/experimental/subscription_intra_process.hpp
  rclcpp/include/rclcpp/experimental/subscription_intra_process_buffer.hpp
  rclcpp/include/rclcpp/generic_subscription.hpp
  rclcpp/include/rclcpp/get_message_type_support_handle.hpp
  rclcpp/include/rclcpp/is_ros_compatible_type.hpp
  rclcpp/include/rclcpp/loaned_message.hpp
  rclcpp/include/rclcpp/node.hpp
  rclcpp/include/rclcpp/node_impl.hpp
  rclcpp/include/rclcpp/publisher.hpp
  rclcpp/include/rclcpp/serialized_message.hpp
  rclcpp/include/rclcpp/subscription.hpp
  rclcpp/include/rclcpp/subscription_base.hpp
  rclcpp/include/rclcpp/subscription_factory.hpp
  rclcpp/include/rclcpp/type_adapter.hpp
  rclcpp/src/rclcpp/executor.cpp
  rclcpp/src/rclcpp/generic_subscription.cpp
  rclcpp/test/msg/String.msg
  rclcpp/test/rclcpp/CMakeLists.txt
  rclcpp/test/rclcpp/node_interfaces/test_node_topics.cpp
  rclcpp/test/rclcpp/test_any_subscription_callback.cpp
  rclcpp/test/rclcpp/test_intra_process_manager.cpp
  rclcpp/test/rclcpp/test_intra_process_manager_with_allocators.cpp
  rclcpp/test/rclcpp/test_loaned_message.cpp
  rclcpp/test/rclcpp/test_publisher_with_type_adapter.cpp
  rclcpp/test/rclcpp/test_subscription.cpp
  rclcpp/test/rclcpp/test_subscription_with_type_adapter.cpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node_impl.hpp
Labels: enhancement

#1663 Fix doc typo
  rclcpp/include/rclcpp/context.hpp
Labels: documentation

#1668 [service] Don't use a weak_ptr to avoid leaking
  rclcpp/include/rclcpp/service.hpp
Labels: bug

#1671 Bump the benchmark timeout for benchmark_action_client
  rclcpp_action/test/benchmark/CMakeLists.txt
Labels: bug

#1675 Fix destruction order in lifecycle benchmark
  rclcpp_lifecycle/test/benchmark/benchmark_lifecycle_client.cpp
Labels: bug

#1673 Declare parameters uninitialized
  rclcpp/include/rclcpp/exceptions/exceptions.hpp
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
  rclcpp/test/rclcpp/test_node.cpp
Labels: enhancement

#1677 Fix occasionally missing goal result caused by race condition
  rclcpp_action/src/server.cpp
Labels: bug
