Repository ros2/rclcpp, pull requests merged in 2021-04, with the labels that each got.

#1452 Add rclcpp_generic, a publisher and subscription for serialized messages
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/create_generic_publisher.hpp
  rclcpp/include/rclcpp/create_generic_subscription.hpp
  rclcpp/include/rclcpp/generic_publisher.hpp
  rclcpp/include/rclcpp/generic_subscription.hpp
  rclcpp/include/rclcpp/node.hpp
  rclcpp/include/rclcpp/node_impl.hpp
  rclcpp/include/rclcpp/rclcpp.hpp
  rclcpp/include/rclcpp/subscription_base.hpp
  rclcpp/include/rclcpp/typesupport_helpers.hpp
  rclcpp/package.xml
  rclcpp/src/rclcpp/generic_publisher.cpp
  rclcpp/src/rclcpp/generic_subscription.cpp
  rclcpp/src/rclcpp/typesupport_helpers.cpp
  rclcpp/test/rclcpp/CMakeLists.txt
  rclcpp/test/rclcpp/test_generic_pubsub.cpp
  rclcpp/test/rclcpp/test_typesupport_helpers.cpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node_impl.hpp
Labels: enhancement, requires-changes

#1598 refactor AnySubscriptionCallback and add/deprecate callback signatures
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/any_subscription_callback.hpp
  rclcpp/include/rclcpp/detail/subscription_callback_type_helper.hpp
  rclcpp/include/rclcpp/function_traits.hpp
  rclcpp/include/rclcpp/parameter_event_handler.hpp
  rclcpp/include/rclcpp/parameter_events_filter.hpp
  rclcpp/include/rclcpp/subscription_factory.hpp
  rclcpp/include/rclcpp/subscription_traits.hpp
  rclcpp/include/rclcpp/time_source.hpp
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
  rclcpp/src/rclcpp/parameter_event_handler.cpp
  rclcpp/src/rclcpp/parameter_events_filter.cpp
  rclcpp/src/rclcpp/time_source.cpp
  rclcpp/test/benchmark/benchmark_executor.cpp
  rclcpp/test/rclcpp/executors/test_executors.cpp
  rclcpp/test/rclcpp/executors/test_static_executor_entities_collector.cpp
  rclcpp/test/rclcpp/node_interfaces/test_node_graph.cpp
  rclcpp/test/rclcpp/strategies/test_allocator_memory_strategy.cpp
  rclcpp/test/rclcpp/test_add_callback_groups_to_executor.cpp
  rclcpp/test/rclcpp/test_any_subscription_callback.cpp
  rclcpp/test/rclcpp/test_create_subscription.cpp
  rclcpp/test/rclcpp/test_memory_strategy.cpp
  rclcpp/test/rclcpp/test_node.cpp
  rclcpp/test/rclcpp/test_parameter_client.cpp
  rclcpp/test/rclcpp/test_parameter_event_handler.cpp
  rclcpp/test/rclcpp/test_publisher_subscription_count_api.cpp
  rclcpp/test/rclcpp/test_qos_event.cpp
  rclcpp/test/rclcpp/test_serialized_message_allocator.cpp
  rclcpp/test/rclcpp/test_subscription.cpp
  rclcpp/test/rclcpp/test_subscription_publisher_count_api.cpp
  rclcpp/test/rclcpp/test_wait_set.cpp
  rclcpp/test/rclcpp/wait_set_policies/test_dynamic_storage.cpp
  rclcpp/test/rclcpp/wait_set_policies/test_static_storage.cpp
  rclcpp/test/rclcpp/wait_set_policies/test_storage_policy_common.cpp
  rclcpp/test/rclcpp/wait_set_policies/test_thread_safe_synchronization.cpp
Labels: enhancement

#1596 Create load_parameters and delete_parameters methods
  rclcpp/include/rclcpp/parameter_client.hpp
  rclcpp/include/rclcpp/parameter_map.hpp
  rclcpp/src/rclcpp/parameter_client.cpp
  rclcpp/src/rclcpp/parameter_map.cpp
  rclcpp/test/rclcpp/test_parameter_client.cpp
  rclcpp/test/resources/test_node/load_parameters.yaml
Labels: enhancement

#1600 Add publishing instrumentation
  rclcpp/include/rclcpp/publisher.hpp
Labels: enhancement

#1496 Unique network flows
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/network_flow_endpoint.hpp
  rclcpp/include/rclcpp/publisher_base.hpp
  rclcpp/include/rclcpp/publisher_options.hpp
  rclcpp/include/rclcpp/subscription_base.hpp
  rclcpp/include/rclcpp/subscription_options.hpp
  rclcpp/src/rclcpp/network_flow_endpoint.cpp
  rclcpp/src/rclcpp/publisher_base.cpp
  rclcpp/src/rclcpp/subscription_base.cpp
  rclcpp/test/rclcpp/test_publisher.cpp
  rclcpp/test/rclcpp/test_subscription.cpp
Labels: enhancement

#1627 Check first parameter type and range before calling the user validation callbacks
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
Labels: bug

#1631 Clarify node parameters docs
  rclcpp/include/rclcpp/node_interfaces/node_parameters_interface.hpp
Labels: documentation

#1634 Increase cppcheck timeout to 500s
  rclcpp/CMakeLists.txt
Labels: bug

#1641 Returns CancelResponse::REJECT while goal handle failed to transit to CANCELING state
  rclcpp_action/include/rclcpp_action/server.hpp
  rclcpp_action/test/test_server.cpp
Labels: bug
