Repository ros2/rclcpp, pull requests merged in 2021-03, with the labels that each got.

#1469 Fix SEGV caused by order of destruction of Node sub-interfaces
  rclcpp/include/rclcpp/service.hpp
  rclcpp/src/rclcpp/node.cpp
  rclcpp_lifecycle/src/lifecycle_node.cpp
Labels: bug

#1575 Add tests for declaring statically typed parameters when undeclared parameters are allowed
  rclcpp/test/rclcpp/test_node.cpp
Labels: enhancement

#1532 Enable qos parameter overrides for the /parameter_events topic
  rclcpp/CMakeLists.txt
  rclcpp/src/rclcpp/detail/resolve_parameter_overrides.cpp
  rclcpp/src/rclcpp/detail/resolve_parameter_overrides.hpp
  rclcpp/src/rclcpp/node.cpp
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
  rclcpp/test/rclcpp/test_qos_parameters.cpp
Labels: enhancement

#1582 Fix doc typo in CallbackGroup constructor
  rclcpp/include/rclcpp/callback_group.hpp
Labels: documentation

#1568 Document design decisions that were made for statically typed parameters
  rclcpp/doc/notes_on_statically_typed_parameters.md
Labels: enhancement

#1514 get_parameters_service_ should return empty if allow_undeclared_ is false
  rclcpp/src/rclcpp/parameter_service.cpp
  rclcpp/test/rclcpp/test_parameter_client.cpp
Labels: enhancement, more-information-needed

#1584 Guard against integer overflow in duration conversion
  rclcpp/src/rclcpp/duration.cpp
  rclcpp/test/rclcpp/test_duration.cpp
Labels: bug

#1554 Add API for checking QoS profile compatibility
  rclcpp/include/rclcpp/exceptions/exceptions.hpp
  rclcpp/include/rclcpp/qos.hpp
  rclcpp/src/rclcpp/qos.cpp
  rclcpp/test/rclcpp/test_qos.cpp
Labels: enhancement

#1602 Fix "oh yeah destructuro"
  rclcpp_lifecycle/src/lifecycle_node_interface_impl.hpp
Labels: bug

#1556 Clock subscription callback group spins in its own thread
  rclcpp/include/rclcpp/node_interfaces/node_time_source.hpp
  rclcpp/include/rclcpp/node_options.hpp
  rclcpp/include/rclcpp/time_source.hpp
  rclcpp/src/rclcpp/node.cpp
  rclcpp/src/rclcpp/node_interfaces/node_time_source.cpp
  rclcpp/src/rclcpp/node_options.cpp
  rclcpp/src/rclcpp/time_source.cpp
  rclcpp/test/rclcpp/test_time_source.cpp
  rclcpp_lifecycle/src/lifecycle_node.cpp
Labels: enhancement, more-information-needed

#1609 Initialize integers in test_parameter_event_handler.cpp to avoid undefined behavior
  rclcpp/test/rclcpp/test_parameter_event_handler.cpp
Labels: enhancement
