Repository ros2/rclcpp, pull requests merged in 2021-02, with the labels that each got.

#1535 clear statistics after window reset (#1531)
  rclcpp/include/rclcpp/create_subscription.hpp
  rclcpp/include/rclcpp/topic_statistics/subscription_topic_statistics.hpp
  rclcpp/test/rclcpp/topic_statistics/test_subscription_topic_statistics.cpp
Labels: bug

#1543 Reference test resources directly from source tree
  rclcpp/test/CMakeLists.txt
  rclcpp/test/rclcpp/CMakeLists.txt
Labels: bug

#1516 Allow timers to keep up the intended rate in MultiThreadedExecutor
  rclcpp/CMakeLists.txt
  rclcpp/include/rclcpp/detail/mutex_two_priorities.hpp
  rclcpp/include/rclcpp/executors/multi_threaded_executor.hpp
  rclcpp/src/rclcpp/detail/mutex_two_priorities.cpp
  rclcpp/src/rclcpp/executors/multi_threaded_executor.cpp
Labels: enhancement

#1522 Enforce static parameter types
  rclcpp/include/rclcpp/exceptions/exceptions.hpp
  rclcpp/include/rclcpp/node.hpp
  rclcpp/include/rclcpp/node_impl.hpp
  rclcpp/include/rclcpp/node_interfaces/node_parameters.hpp
  rclcpp/include/rclcpp/node_interfaces/node_parameters_interface.hpp
  rclcpp/src/rclcpp/node.cpp
  rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
  rclcpp/test/benchmark/benchmark_node_parameters_interface.cpp
  rclcpp/test/benchmark/benchmark_parameter_client.cpp
  rclcpp/test/rclcpp/test_node.cpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
  rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node_impl.hpp
  rclcpp_lifecycle/src/lifecycle_node.cpp
  rclcpp_lifecycle/test/test_lifecycle_node.cpp
Labels: enhancement

#1558 Fix documented example in create_publisher
  rclcpp/include/rclcpp/node.hpp
Labels: documentation

#1560 [dashing] Fix documented example in create_publisher (#1558)
  rclcpp/include/rclcpp/node.hpp
Labels: documentation

#1559 [foxy] Fix documented example in create_publisher (#1558)
  rclcpp/include/rclcpp/node.hpp
Labels: documentation

#1564 Fix benchmark test failure introduced in #1522
  rclcpp/test/benchmark/benchmark_parameter_client.cpp
Labels: bug

#1565 [foxy] node_handle must be destroyed after client_handle to prevent memory leak (#1562)
  rclcpp_action/src/client.cpp
Labels: bug
